import Head from 'next/head'
import Navbar from '../components/Navbar'
import Heading from '@/components/Heading'
import Footer from '@/components/Footer'
import Hero from '@/components/Hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>KiCos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main>
        <Hero />
        <div className="container mx-auto py-10 px-4" id='aboutus'>
            <div className='pl-8'>
            <Heading title="About KiRentCos" />
            </div>
        <div className="max-w-[800px] pl-8">
            <p className="text-gray-700 text-[20px]">
            Ki Rental Cosplay & Jual Kostum mempunyai produk kostum Cosplay dengan brand terbaik. 
            Seperti Brand Uwowo, Manmei, Manmei Tobao, DokiDoki-R
            </p>
        </div>
        </div>
      </main>

      <footer>
        <Footer />
      </footer>
    </>
  )
}
