import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
import AboutUs from '@/components/AboutUs'

export default function Home() {
  return (
    <>
      <Head>
        <title>KiCos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main>
        <Hero />
        <AboutUs />
      </main>

      <footer>
        <Footer />
      </footer>
    </>
  )
}
